name: agri_supply_chain
description: A Flutter mobile app for agriculture supply chain transparency with QR scanning and traceability features.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Navigation
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.0
  
  # State Management
  provider: ^6.1.1
  
  # Networking
  http: ^1.1.0
  dio: ^5.3.3
  
  # QR Code
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0
  
  # Camera & Image
  camera: ^0.10.5+5
  image_picker: ^1.0.4
  
  # Storage & Persistence
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  
  # Location
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Utils
  uuid: ^4.2.1
  intl: ^0.18.1
  url_launcher: ^6.2.1
  
  # Charts & Visualization
  fl_chart: ^0.64.0
  
  # Permissions
  permission_handler: ^11.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700